import { Router } from "express";
import authRoutes from "./auth.routes.js";
import cartaRoutes from "./carta.routes.js";
import colecaoRoutes from "./colecao.routes.js";
import pacoteRoutes from "./pacote.routes.js";
import boosterRoutes from "./booster.routes.js";
import criacaoRoutes from "./criacao.routes.js";
import laboratorioRoutes from "./laboratorio.routes.js";
import missaoRoutes from "./missao.routes.js";
import evolucaoRoutes from "./evolucao.routes.js";
import streakRoutes from "./streak.routes.js";
import tituloRoutes from "./titulo.routes.js";
import missaoDiariaRoutes from "./missaoDiaria.routes.js";
import progressaoRoutes from "./progressao.routes.js";
import guildaRoutes from "./guilda.routes.js";
import bossGuildaRoutes from "./bossGuilda.routes.js";
import sessaoTrocaRoutes from "./sessaoTroca.routes.js";
import rankingSemanalRoutes from "./rankingSemanal.routes.js";
import usuarioRoutes from "./usuario.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/cartas", cartaRoutes);
router.use("/colecao", colecaoRoutes);
router.use("/pacotes", pacoteRoutes);
router.use("/boosters", boosterRoutes);
router.use("/criacao", criacaoRoutes);
router.use("/laboratorio", laboratorioRoutes);
router.use("/missoes", missaoRoutes);
router.use("/evolucao", evolucaoRoutes);
router.use("/streak", streakRoutes);
router.use("/titulos", tituloRoutes);
router.use("/missao-diaria", missaoDiariaRoutes);
router.use("/progressao", progressaoRoutes);
router.use("/guildas", guildaRoutes);
router.use("/boss-guilda", bossGuildaRoutes);
router.use("/sessao-troca", sessaoTrocaRoutes);
router.use("/ranking", rankingSemanalRoutes);
router.use("/usuarios", usuarioRoutes);

export default router;
